modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/crawkatt/meica_mod/issues" #optional
#logoFile="meicamod.png"

[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors="${mod_authors}" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

# The description text for the mod (multi line!) (#mandatory)
description="""
Mod about the Vtuber Meica05 that includes Brotecitos in the world, new ores, new biome, weapons, and much more.

Among the main features:

- Meica Forest Biome: Explore a new and dangerous exclusive biome. This biome features large trees, tameable brotecitos, and\
a dense green fog that has detrimental effects on you as you spend more time in it, offering a new and exciting environment for your adventures.

- Mineral Brotenite: Discover "Brotenite", a new and rare mineral more valuable than Netherite and only found inside the\
Brotenite Geodes, located within the Meica Forest.

- Brotenite Armor: Equip yourself with the Brotenite armor, which protects you from the damaging effects of the Meica Forest, allowing you\
to venture into the forest and collect resources more safely.

Why download Meica Mod?
The Meica Mod is ideal for Meica05 fans and those seeking a Minecraft experience enriched with content inspired by their favorite Vtuber.\
With new mechanics, a themed biome, and custom elements, this mod offers a fun way to bring your passion for Meica into the world of Minecraft.

Compatibility:
Client and Server: The Meica Mod requires installation on both client and server to ensure that all features, including the Meica Forest biome and\
Brotenite Armor, are available in both environments.

Realistic or lighting-changing shaders are incompatible: Because lighting-changing shaders also change how fog works,\
it can happen that the greenish fog is rendered in the Meica Forest biome or is partially displayed without its characteristic color.\
It does not directly affect as an incompatibility that makes it impossible to play with such shaders,\
but it is recommended to disable them for a better experience when entering Meica Forest.
"""

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="terrablender"
mandatory=true
versionRange="${terrablender_version_range}"
ordering="NONE"
side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"